### ISSUE TITLE
[Feature Request] Null-Safety support

### ISSUE THREAD

**Issue by waseemarain4u** [muhammadidrees/bloc_rest_api#2]
Thanks for the awesome package.

Please migrating this package to null-safety would help a lot. :)

Here's an official guide from dart doc
[migration-guide](https://dart.dev/null-safety/migration-guide)

**Comment by muhammadidrees** [comment]
Hello @waseemarain4u, :wave: 
Thanks for opening an issue! 

I am planning to pre-release the null-safety version in the coming week. :smile:

**Comment by muhammadidrees** [comment]
Just released the pre-release version of null-safety. :partying_face:

Thank you for your patience. Closing the issue now. :smile:
